In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r'C:\Users\divya\OneDrive\Desktop\Project\Customer Call List.xlsx')

In [4]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [5]:
df_new = df['Phone_Number'].str.replace(r'\D' , '',regex = True)

In [6]:
df['Phone_Number'] = df['Phone_Number'].where(df_new.isna(),df_new)

In [7]:
df['Phone_Number'] = df['Phone_Number'].astype(str)

In [8]:
df['Phone_Number'] = df['Phone_Number'].str[:3] + '-' + df['Phone_Number'].str[3:6]  + '-' + df['Phone_Number'].str[6:10]

In [9]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,706-695-0392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True

In [10]:
df.groupby('Do_Not_Contact')['CustomerID'].count()

Do_Not_Contact
N      4
No     9
Y      1
Yes    3
Name: CustomerID, dtype: int64

In [11]:
df['Paying Customer'] = df['Paying Customer'].apply(lambda x: 'Yes' if str(x).startswith(('Y','y')) else 'No' if str(x).startswith(('N','n')) else x)

In [12]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].apply(lambda x: 'Yes' if str(x).startswith(('Y','y')) else 'No' if str(x).startswith(('N','n')) else x)

In [13]:
df.tail()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Yes,No,True
18,1019,Creed,Braton,--,N/a,No,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,True

In [14]:
df[['Street','State']] = df['Address'].str.split(',' , n=1,expand = True)

In [15]:
df = df.drop_duplicates()

In [16]:
df.drop(columns = {'Not_Useful_Column'},inplace = True)

In [17]:
 df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,NaN
2,1003,Walter,/White,706-695-0392,298 Drugs Driveway,No,No,298 Drugs Driveway,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,980 Paper Avenue,"Pennsylvania, 18503"
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Yes,No,123 Dragons Road,NaN

In [18]:
df['Last_Name'] = df['Last_Name'].str.replace(r'^[^a-zA-Z]+', '', regex=True)

In [19]:
df['State'] = df['State'].fillna('Unknown')

In [20]:
df['State'] = df['State'].fillna('Not Mentioned')

In [21]:
df['Phone_Number'].dtype

In [22]:
df['Phone_Number'] = df['Phone_Number'].str.replace('--','',regex=True)

In [23]:
df['Phone_Number']=df['Phone_Number'].fillna('')

In [24]:
df = df[df['Phone_Number'] != '']

In [25]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,Unknown
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,No,No,298 Drugs Driveway,Unknown
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,980 Paper Avenue,"Pennsylvania, 18503"
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Yes,No,123 Dragons Road,Unknown
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,Unknown
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,No,98 Clue Drive,Unknown
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Yes,No,2394 Hogwarts Avenue,Unknown
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,No,2039 Main Street,Unknown
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,Unknown
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,No,No,214 HR Avenue,Unknown
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,Unknown
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Yes,No,3498 Super Lane,Unknown
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine

In [26]:
del df['Address']

In [27]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,State
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street,Unknown
2,1003,Walter,White,706-695-0392,No,No,298 Drugs Driveway,Unknown
3,1004,Dwight,Schrute,123-543-2345,Yes,Yes,980 Paper Avenue,"Pennsylvania, 18503"
4,1005,Jon,Snow,876-678-3469,Yes,No,123 Dragons Road,Unknown
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,Unknown
7,1008,Sherlock,Holmes,876-678-3469,No,No,98 Clue Drive,Unknown
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York
11,1012,Harry,Potter,706-695-0392,Yes,No,2394 Hogwarts Avenue,Unknown
12,1013,Don,Draper,123-543-2345,Yes,No,2039 Main Street,Unknown
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,Unknown
14,1015,Toby,Flenderson_,304-762-2467,No,No,214 HR Avenue,Unknown
15,1016,Ron,Weasley,123-545-5421,No,No,2395 Hogwarts Avenue,Unknown
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania
17,1018,Clark,Kent,706-695-0392,Yes,No,3498 Super Lane,Unknown
19,1020,Anakin,Skywalker,876-678-3469,Yes,No,910 Tatooine Road,Tatooine